### ISSUE TITLE
explain pseudo-multitouch in the datasheet

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/Trill#11]
@george-norton write 

> documentation states that the 2D sensors only support "pseudo multitouch" without providing any real details. I am imagining that the axes are being treated independently and it becomes difficult to track which x and y report are a pair? I can work with a single touch + contact count for emulating a mouse, but I am also working on some USB HID digitiser stuff with Azoteq and MaxTouch sensors. It would be great if I could somehow reliably track 2 or 3 fingers.

What we mean by pseudo-multitouch here is that there are 15 capacitive channels on each axis. What you get is a list of the touches on the horizontal axis and a list of touches on the vertical axis. If you have two touches, you will not know which vertical touch corresponds to which horizontal touch. Also, if you have multiple touches aligned on the same vertical axis they will look like a single touch on the horizontal axis.

Worth adding this to the datasheet

**Comment by mxa** [comment]
Proposed new table footnote 1, getting rid of the term "pseudo-multi-touch" entirely:

Trill 2-axis pads (Trill Square and Trill Hex) do not support multi-touch. While they are able to detect if more than one finger is touching the pad, they are unable to determine the exact locations of multiple touch points unambiguously. The sensors with 2-axis pads feature a square matrix configuration of pads, with the 30 channels of capacitive sensing distributed between two axes (15 channels per axis). A single touch results in the return of one pair of X/Y coordinates, which are accurate. However, with multiple touches present, Trill will register all touches and return them as two lists, one list for touches on the X axis and the other list for touches on the Y axis. Unfortunately, there is no way to accurately pair these X and Y values to produce distinctive touch locations.
