### ISSUE TITLE
Trill Craft R and C values

### ISSUE THREAD

**Issue by fenicento** [BelaPlatform/Trill#2]
It is not specified what use and values the resistors and capacitors on boards have. I'll try to make a guess for the ones in the Trill Craft, but it would be nice to integrate these info in the repo.

R1 and R2: I2C pull-up resistors, 4.7kΩ
R3 and R4: I2C address pin pull down resistor, 4.7kΩ
C1: decoupling capacitor, 0.1µF
C2: Cmod capacitor for Cypress CSA sensing method ([described here](http://dlm.cypress.com.edgesuite.net/akdlm/old/design_resources/developer_kits/contents/cy3280_24x94_universal_capsense_controller_board_16.pdf)), 1nF

are these values correct?

**Comment by giuliomoro** [comment]
sorry BOMs were missing. They are there now
