### ISSUE TITLE
Request: Trill Craft (as a component) KiCAD library

### ISSUE THREAD

**Issue by DocSunset** [BelaPlatform/Trill#5]
It would be fantastic to have KiCAD symbols and footprints for integrating Trill Craft into schematics and PCBs, similar to the library files available for the other Trill devices.

**Comment by mxa** [comment]
Say hi to a craft symbol, footprint and 3d model to use in your projects.

![grafik](https://github.com/BelaPlatform/Trill/assets/1220707/b3ef2b4b-c434-4747-b9ba-8de889061535)
![grafik](https://github.com/BelaPlatform/Trill/assets/1220707/79ff4674-32a7-4c58-8ee2-44a55692770a)
![grafik](https://github.com/BelaPlatform/Trill/assets/1220707/3bc77f8f-1501-4565-97d7-7b8659e82eb6)

**Comment by mxa** [comment]
The footprint still needs to be verified in the physical world, feedback welcome, especially on the size and shape of the smd pads.
